# Generated by Django 5.2.1 on 2025-05-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField()),
                ('Last_Name', models.CharField()),
                ('Number', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField()),
            ],
        ),
    ]
