# Generated by Django 5.2.1 on 2025-05-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='Number',
            field=models.CharField(),
        ),
    ]
