# Generated by Django 5.2.1 on 2025-05-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0002_alter_clientuser_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField()),
                ('Item_price', models.CharField()),
                ('Item_details', models.CharField()),
                ('Item_catogary', models.CharField()),
                ('Item_img', models.CharField()),
            ],
        ),
    ]
