# Generated by Django 5.2.1 on 2025-05-31 11:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0003_fooditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='Image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='items/'),
            preserve_default=False,
        ),
    ]
