# Generated by Django 5.2.1 on 2025-05-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0004_fooditem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='Image',
            field=models.ImageField(upload_to='media/items/'),
        ),
    ]
