# Generated by Django 5.2.1 on 2025-05-31 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0005_alter_fooditem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='Item_img',
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='Item_details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='Item_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='Item_catogary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Name', to='cooking.itemlist'),
        ),
    ]
