# Generated by Django 5.2.1 on 2025-05-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0006_itemlist_remove_fooditem_item_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='Category_name',
            field=models.CharField(),
        ),
    ]
