# Generated by Django 5.2.1 on 2025-06-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0008_booktable'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='media/about/')),
                ('title', models.CharField()),
                ('Details', models.TextField()),
            ],
        ),
    ]
